services:
  app:
    image: todo-frontend
    container_name: todo-frontend 
    build: 
      context: ./todo-frontend
      dockerfile: Dockerfile
    environment:
      # In production we must change the value of the url to the public url relative to the reverse proxy
      VITE_BACKEND_URL: http://localhost:8080/api
    networks:
      - private_proxy_network  # private network (proxy --> app, server)
  server:
    image: todo-backend
    container_name: todo-backend
    environment:
      MONGO_URL: mongodb://the_username:the_password@mongodb_server:27017/the_database
      REDIS_URL: redis://redis_server:6379
    networks:
      - private_proxy_network  # private network (proxy --> app, server)
      - private_server_network  # private network (server -->redis_server, mongo_server)
  mongo:
    image: mongo
    container_name: mongodb_server
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    networks:
      - private_server_network  # private network (server -->redis_server, mongo_server)
  redis:
    image: redis:latest
    container_name: redis_server
    volumes:
      - redis_data:/data
    networks:
      - private_server_network  # private network (server -->redis_server, mongo_server)
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server
    networks:
      - private_proxy_network  # private network (proxy --> app, server)
      - public_network  # private network (server -->redis_server, mongo_server)
networks:
  public_network:
    # External Network
  private_proxy_network:
    internal: true  # Private [ proxy ---> app, server ]Network
  private_server_network:
    internal: true  # Private [ server ---> redis_server, mongo_server ] Network
volumes:
  mongo_data:
  redis_data:

