services:
  app:
    image: todo-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:                
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    container_name: todo-backend-dev
    environment:
      MONGO_URL: mongodb://the_username:the_password@mongo_server:27017/the_database
      REDIS_URL: redis://redis_server:6379
    networks:
      - public_network  # external network
      - private_network  # private network 
  mongo:
    image: initialized-mongo
    container_name: mongo_server
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    networks:
      - private_network
  redis:
    image: redis:latest
    container_name: redis_server
    volumes:
      - redis_data:/data
    networks:
      - private_network
volumes:
  mongo_data:
  redis_data:
networks:
  public_network:
    # External Network
  private_network:
    internal: true  # Private Network